// <auto-generated />
using System;
using Billetterie.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Billetterie.Infrastructure.Migrations
{
    [DbContext(typeof(BilletterieDbContext))]
    [Migration("20260915192556_AddContraintesMetier")]
    partial class AddContraintesMetier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Billetterie.Domain.Entities.Billet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeUnique")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("DateUtilisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<Guid>("TypeBilletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodeUnique")
                        .IsUnique();

                    b.HasIndex("ReservationId");

                    b.HasIndex("TypeBilletId");

                    b.ToTable("Billets");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Evenement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganisateurId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisateurId");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Organisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatutValidation")
                        .HasColumnType("integer");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ValideParUtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Organisateurs");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StatutPaiement")
                        .HasColumnType("integer");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.TypeBillet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("QuantiteTotale")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteVendue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.ToTable("TypeBillets", t =>
                        {
                            t.HasCheckConstraint("CK_TypeBillet_QuantiteVendue", "\"QuantiteVendue\" <= \"QuantiteTotale\"");
                        });
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Billet", b =>
                {
                    b.HasOne("Billetterie.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Billets")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billetterie.Domain.Entities.TypeBillet", "TypeBillet")
                        .WithMany("Billets")
                        .HasForeignKey("TypeBilletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("TypeBillet");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Evenement", b =>
                {
                    b.HasOne("Billetterie.Domain.Entities.Organisateur", "Organisateur")
                        .WithMany("Evenements")
                        .HasForeignKey("OrganisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisateur");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Organisateur", b =>
                {
                    b.HasOne("Billetterie.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne("Organisateur")
                        .HasForeignKey("Billetterie.Domain.Entities.Organisateur", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Billetterie.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Reservations")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.TypeBillet", b =>
                {
                    b.HasOne("Billetterie.Domain.Entities.Evenement", "Evenement")
                        .WithMany("TypeBillet")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Evenement", b =>
                {
                    b.Navigation("TypeBillet");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Organisateur", b =>
                {
                    b.Navigation("Evenements");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Billets");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.TypeBillet", b =>
                {
                    b.Navigation("Billets");
                });

            modelBuilder.Entity("Billetterie.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("Organisateur");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
